### ISSUE TITLE
Feature Extract backbone

### ISSUE THREAD

**Issue by Lucky-Light-Sun** [DarrenZZhang/MITH#2]
你好，论文中的 feature backbone 指的是 ViT 和GPT-2 分别提取 文本和图像信息。但是我发现代码中模型命名为CLIP。我想问一下CLIP的image和text特征提取部分是 ViT 和 GPT-2吗？这是自己训练/微调的吗，还是直接使用别人预训练的模型呢？如果是使用别人预训练的模型，方便给一下官方出处的链接吗。

代码部分

https://github.com/DarrenZZhang/MITH/blob/159bbc7fad6d6cb41d40fc1fdf0e169054de71ea/hash_model.py#L250-L261

论文描述
![image](https://github.com/DarrenZZhang/MITH/assets/60919766/df1e6f72-a967-4650-ab7a-7ebd1b61ac5d)

**Comment by sky-wz** [comment]
我们的方法是微调的CLIP（包括ViT和GPT2），可以在官网下载，也可以在下面百度网盘链接下载（ViT-B-32.pt） link：https://pan.baidu.com/s/1ZyDTR2IEHlY4xIdLgxtaVA password：kdq7

**Comment by Lucky-Light-Sun** [comment]
> 我们的方法是微调的CLIP（包括ViT和GPT2），可以在官网下载，也可以在下面百度网盘链接下载（ViT-B-32.pt） link：https://pan.baidu.com/s/1ZyDTR2IEHlY4xIdLgxtaVA password：kdq7

你好，是自己微调的吗，能方便给一下官网下载的link吗

**Comment by sky-wz** [comment]
CLIP 官方下载地址 "ViT-B/32": "https://openaipublic.azureedge.net/clip/models/40d365715913c9da98579312b702a82c18be219cc2a73407c4526f58eba950af/ViT-B-32.pt",
